// 301 redirects from the old decrisisspecialist.com (Wix) URL structure to
// the new information architecture, so existing SEO/backlinks keep working.

const corePages: [string, string][] = [
  ["/wie-zijn-wij", "/over-ons"],
  ["/over-mij", "/over-ons/kernteam"],
  ["/about1", "/over-ons"],
  ["/about-3", "/over-ons"],
  ["/kopie-van-wie-zijn-wij", "/over-ons"],
  ["/visie-en-missie", "/over-ons"],
  ["/onze-diensten", "/diensten"],
  ["/ambulante-begeleiding", "/diensten/ambulante-begeleiding"],
  ["/opvoedingsondersteuning", "/diensten/opvoedingsondersteuning"],
  ["/trainingen-op-maat", "/diensten/trainingen-op-maat"],
  ["/trajecten-voor-thuiszitters", "/diensten/trajecten-voor-thuiszitters"],
  ["/crisis-interventie", "/diensten/crisis-interventie"],
  ["/coachingstrajecten", "/diensten/coachingstrajecten"],
  ["/counseling", "/diensten/counseling"],
  ["/oplossingsgericht-coachen", "/diensten/oplossingsgericht-coachen"],
  ["/psychosociale-begeleiding", "/diensten/psychosociale-begeleiding"],
  ["/voor-particulieren", "/over-ons/doelgroep/particulieren"],
  ["/voor-ouders-en-hun-kinderen", "/over-ons/doelgroep/ouders-en-kinderen"],
  ["/voor-bedrijven", "/over-ons/doelgroep/bedrijven"],
  ["/voor-zorginstellingen", "/over-ons/doelgroep/zorginstellingen"],
  ["/voor-onderwijsinstellingen", "/over-ons/doelgroep/onderwijsinstellingen"],
  ["/voor-mensen-die-vastlopen", "/over-ons/doelgroep/mensen-die-vastlopen"],
  ["/voor-wie-zijn-wij", "/over-ons/doelgroep"],
  ["/enkele-referenties", "/referenties"],
  ["/klachten-procedure", "/klachtenprocedure"],
  ["/algemene-bepalingen-voorwaarden", "/voorwaarden"],
];

// Old Wix utility/embed pages with no direct new-site equivalent.
const utilityPages: [string, string][] = [
  ["/interessante-artikels", "/kennisbank"],
  ["/blog1", "/kennisbank"],
  ["/quizlets", "/kennisbank"],
  ["/facebook-pagina", "/"],
  ["/pinterest-borden", "/kennisbank"],
  ["/online-classrooms", "/kennisbank"],
  ["/on-the-spot-answergarden", "/kennisbank"],
  ["/events", "/"],
  ["/projects-2", "/"],
];

// Every migrated knowledge-base article — same slug, now namespaced under
// /kennisbank. Keep in sync with content/kennisbank/*.mdx.
const kennisbankSlugs = [
  "maslow",
  "methodiek-triple-c",
  "methodiek-oplossingsgericht-werken",
  "meewerkend-coach-de-werkwijze",
  "aanpak-van-agressie",
  "bejegening-tips-voor-omgaan-met-ppd-nos",
  "mijn-wortels",
  "inhoud-training-de-escalerend-werken",
  "actief-luisteren-de-techniek",
  "hoe-angst-werkt",
  "rotswater-schaal",
  "5-domeinen-van-emotionele-intelligentie",
  "affirmaties",
  "de-schaal-van-gevaar",
  "disharmonische-ontwikkelingsprofiel",
  "de-wet-van-wederkerigheid",
  "gastlessen",
  "de-vuur-serie",
  "tools-complexe-zorg",
  "dankbaarheid",
  "de-pinta-serie",
  "probleemgedrag-categorie",
  "werken-aan-een-positieve-zelfbeeld",
  "probleem-analyse",
  "gedrag-is-niet-perse-vreemd",
  "the-playstation-casus",
  "confronterende-en-begr-interventies",
  "werken-met-de-src-analyse",
  "veerkracht-tips",
  "pictogrammen",
  "de-roos-van-leary",
  "gronden-en-centreren",
  "praktische-zaken-trainingen-en-cursussen",
  "training-de-escalerend-werken",
  "methodiek-ervaringsordening",
  "vier-helpende-gedachtes",
  "schetsen-van-de-complexe-zorg-missie",
  "de-gehechtsheidstherie",
  "opleiding",
  "actief-luisteren",
  "meewerkend-coach-de-strategie",
  "oorzaken-van-probleemgedrag-achterhalen",
  "over-zelfinzicht",
  "werken-aan-zelfredzaamheid",
  "nick-vujicic",
  "de-traan-serie",
  "ei-en-werknemers",
  "e-i-voor-het-bedrijfsleven",
  "gentle-teaching-formulieren-set",
  "crisisrapportage",
  "presentaties-en-lezingen",
  "signaleringsplannen",
  "het-stoplicht",
  "tips-omgaan-met-werkdruk",
  "sancties",
  "cv",
  "bouwstenen-van-veerkracht",
  "emotionele-intelligentie",
  "cce-vragenlijst-kwaliteit-van-bestaan",
  "empathie-in-stappen",
  "e-i-voor-particulieren",
  "tips-omgaan-met",
  "531-oefening",
  "inhoudsopgave-verbale-agressie",
  "zelfsturend-vermogen-multimedia",
  "sandwich-techniek",
  "versterken-van-positieve-zelfbeeld",
  "training-omgaan-met-verbal-aggressive",
  "feedbackpuntenkaarten",
  "interventie-tempo-en-taken-aanpassen",
  "expeditie-robinson",
  "sociaal-disfunctioneren",
  "leren-omgaan-met-emoties",
  "werken-aan-emotie-regulatie",
  "sport-en-outdoor",
  "kwaliteitsvragen-ouders-kinderen",
];

export const legacyRedirects: { source: string; destination: string; permanent: true }[] = [
  ...corePages.map(([source, destination]) => ({ source, destination, permanent: true as const })),
  ...utilityPages.map(([source, destination]) => ({ source, destination, permanent: true as const })),
  ...kennisbankSlugs.map((slug) => ({
    source: `/${slug}`,
    destination: `/kennisbank/${slug}`,
    permanent: true as const,
  })),
];
